#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config active_border_color '#C3BAC6'
bspc config normal_border_color '#C3BAC6'
bspc config focused_border_color '#F8BD96'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Alacritty desktop='^1' follow=on
bspc rule -a Code desktop='^2' follow=on
bspc rule -a firefox desktop='^3' follow=on
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a discord desktop='^4'

# My startups
~/.fehbg &
setxkbmap -model pc105 -layout us,ru -option grp:alt_shift_toggle
xrandr --output eDP --gamma 1:1:1 --brightness 1.04 --dpi 120
xset r rate 290 30
$HOME/.config/polybar/launch.sh
# $HOME/.config/conky/Altair/start.sh
# wal -R
picom &
xsetroot -cursor_name left_ptr
numlockx on
sudo auto-cpufreq --daemon
